import = [
    "$DOTILES/alacritty/themes/dracula.toml"
]

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 7
y = 7

[selection]
save_to_clipboard = true

# this is needed for true colors in tmux and nvim
[env]
term = "xterm-256color"
