import type { ExtensionAPI } from "@mariozechner/pi-coding-agent"
import { Type } from "typebox"
import {
  createTemporaryWorkspaceCreateParameters,
  createTemporaryWorkspaceDeleteParameters,
  createTemporaryWorkspaceHandler,
  createTemporaryWorkspaceListParameters,
} from "./lib/temporary-workspace"

export default function temporaryWorkspaceExtension(pi: ExtensionAPI) {
  const executeTemporaryWorkspace = createTemporaryWorkspaceHandler()

  pi.registerTool({
    name: "temporary_workspace_create",
    label: "Create Temporary Workspace",
    description:
      "Create a process-owned disposable workspace with an autogenerated opaque ID and path. Takes no arguments. Prefer pipes or stdout when no file is needed. Use this for disposable files, downloads, logs, browser captures, installs, tests, and builds. Move retained outputs elsewhere before deletion. This is the only approved scratch location.",
    promptSnippet:
      "Create a managed disposable workspace for scratch files, downloads, logs, screenshots, tests, and builds",
    promptGuidelines: [
      "Before creating any disposable file, directory, download, log, screenshot, test artifact, or build artifact, use temporary_workspace_create. Prefer stdout or pipes when no file is needed.",
      "Do not create scratch files or directories under /tmp, $TMPDIR, ./tmp, ./temp, or other ad hoc temporary paths. Use the path returned by temporary_workspace_create.",
      "Move outputs that must survive to an intentional project or output path before temporary_workspace_delete.",
    ],
    parameters: createTemporaryWorkspaceCreateParameters(Type),
    async execute(_toolCallId, _params, signal, _onUpdate, ctx) {
      return executeTemporaryWorkspace({ action: "create" }, signal, ctx.cwd)
    },
  })

  pi.registerTool({
    name: "temporary_workspace_list",
    label: "List Temporary Workspaces",
    description:
      "List live managed temporary workspaces owned by this process. Takes no arguments.",
    promptSnippet: "List live managed temporary workspaces owned by this process",
    parameters: createTemporaryWorkspaceListParameters(Type),
    async execute(_toolCallId, _params, signal, _onUpdate, ctx) {
      return executeTemporaryWorkspace({ action: "list" }, signal, ctx.cwd)
    },
  })

  pi.registerTool({
    name: "temporary_workspace_delete",
    label: "Delete Temporary Workspace",
    description:
      "Delete a managed temporary workspace using the opaque ID returned by temporary_workspace_create. Move retained outputs elsewhere first.",
    promptSnippet:
      "Delete a managed temporary workspace after moving retained outputs elsewhere",
    promptGuidelines: [
      "Only delete a workspace after moving retained outputs elsewhere.",
    ],
    parameters: createTemporaryWorkspaceDeleteParameters(Type),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      return executeTemporaryWorkspace(
        { action: "delete", id: params.id },
        signal,
        ctx.cwd,
      )
    },
  })
}
