import type { ExtensionAPI } from "@mariozechner/pi-coding-agent"
import { Type } from "typebox"
import {
  createTemporaryWorkspaceCreateParameters,
  createTemporaryWorkspaceDeleteParameters,
  createTemporaryWorkspaceHandler,
  createTemporaryWorkspaceListParameters,
} from "./lib/temporary-workspace"

export default function temporaryWorkspaceExtension(pi: ExtensionAPI) {
  const executeTemporaryWorkspace = createTemporaryWorkspaceHandler()

  pi.registerTool({
    name: "temporary_workspace_create",
    label: "Create Temporary Workspace",
    description:
      "Create a process-owned disposable workspace with an autogenerated opaque ID and path. Takes no arguments. Prefer pipes or stdout when no file is needed. Use this for disposable files, downloads, logs, browser captures, installs, tests, and builds. Move retained outputs elsewhere before deletion.",
    promptSnippet:
      "Prefer pipes or stdout over temporary files. When scratch storage is required, call temporary_workspace_create with no arguments, use its returned path and ID, move retained outputs out, then call temporary_workspace_delete with the returned ID. Do not create /tmp, tmp/, or temp/ files with shell commands.",
    parameters: createTemporaryWorkspaceCreateParameters(Type),
    async execute(_toolCallId, _params, signal, _onUpdate, ctx) {
      return executeTemporaryWorkspace({ action: "create" }, signal, ctx.cwd)
    },
  })

  pi.registerTool({
    name: "temporary_workspace_list",
    label: "List Temporary Workspaces",
    description:
      "List live managed temporary workspaces owned by this process. Takes no arguments.",
    parameters: createTemporaryWorkspaceListParameters(Type),
    async execute(_toolCallId, _params, signal, _onUpdate, ctx) {
      return executeTemporaryWorkspace({ action: "list" }, signal, ctx.cwd)
    },
  })

  pi.registerTool({
    name: "temporary_workspace_delete",
    label: "Delete Temporary Workspace",
    description:
      "Delete a managed temporary workspace using the opaque ID returned by temporary_workspace_create. Move retained outputs elsewhere first.",
    parameters: createTemporaryWorkspaceDeleteParameters(Type),
    async execute(_toolCallId, params, signal, _onUpdate, ctx) {
      return executeTemporaryWorkspace(
        { action: "delete", id: params.id },
        signal,
        ctx.cwd,
      )
    },
  })
}
