git:
  diffRenderers:
    - command: difft --color=always --background=dark
      type: extDiff
gui:
  theme:
    selectedLineBgColor:
      - reverse
keybinding:
  commits:
    resetCherryPick: <c-r>
