[metadata]
name = "text"
description = "Find and select text from files"
requirements = ["rg"]

[source]
command = [
  "rg . --no-heading --line-number --colors 'match:fg:white' --colors 'path:fg:blue' --color=always",
  "rg . --no-heading --line-number --hidden --colors 'match:fg:white' --colors 'path:fg:blue' --color=always",
]
ansi = true
output = "{strip_ansi|split:\\::..2}"

[preview]
command = "head -100 '{strip_ansi|split:\\::0}'"
offset = '{strip_ansi|split:\::1}'

[ui]
preview_panel = { header = '{strip_ansi|split:\::..2}' }

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "Open file in editor at line"
command = "nvim '+{strip_ansi|split:\\::1}' '{strip_ansi|split:\\::0}'"
mode = "execute"
