# For a full list of active aliases, run `alias`.
#
# ALIASES ---------------------------------------------------------------------
alias vim="nvim"
alias v="nvim ."
alias zshconfig="nvim ~/Projects/dotfiles/zsh/zsh.rc"
alias zshalias="nvim ~/Projects/dotfiles/zsh/aliases.zsh"
alias arm="env /usr/bin/arch -arm64 /bin/zsh"
alias intel="env /usr/bin/arch -x86_64 /bin/zsh"
alias ip="ipconfig getifaddr en0"
alias tt="ttyper"
alias ttjs="ttyper -l javascript"
alias python="python3"
alias mouse="bash $DOTFILES/scripts/mouse.sh"
alias summary="pbpaste | llm --system 'summary bullet points' -s"
alias article="pbpaste | llm --system 'You are an expert technical writer. I will give you a title and some bulletpoints. You will will write a friendly and engaging article in simple language.' -s"
alias windows="bash ~/Projects/dotfiles/scripts/tmux-windows.sh"
alias ld="lazydocker"
alias lg="lazygit"

# LOCATION ALIASES -----------------------------------------------------------------
alias desktop="cd ~/Desktop"
alias downloads="cd ~/Downloads"
alias documents="cd ~/Documents"
alias icloud="cd '~/Library/Mobile Documents/com~apple~CloudDocs'"
alias notes="cd '~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes'"
alias dotfiles="cd ~/Projects/dotfiles"
alias pp="cd ~/Projects"
alias link-dotfiles="bash ~/Projects/dotfiles/install/bootstrap.sh"
alias ssh="export TERM=xterm-256color; ssh"
