import { homedir, tmpdir } from "node:os"
import { realpath } from "node:fs/promises"
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path"

export type DestructiveShellRisk = {
  category: string
  matched: string
  subject: string
  hardBlock?: boolean
  remediation?: string
}

const TEMP_PATH = String.raw`(?:(?:\/private)?\/tmp|\$\{?TMPDIR\}?|(?:[^\s;&|<>"']+\/)*(?:tmp|temp)(?![A-Za-z0-9_-]))(?:\/[^\s;&|<>"']*)?`
const TEMP_PATH_PATTERN = new RegExp(TEMP_PATH, "i")
const TEMP_CREATION_PATTERNS: RegExp[] = [
  /\bmktemp\b/i,
  /\b(?:tempfile\.(?:TemporaryDirectory|NamedTemporaryFile|mkdtemp|mkstemp)|(?:fs|require\s*\(\s*["']fs["']\s*\))\.(?:mkdtemp|mkdtempSync)|Deno\.(?:makeTempDir|makeTempFile))\s*\(/i,
  new RegExp(String.raw`\bmkdir\b[^\n;&|]*${TEMP_PATH}`, "i"),
  new RegExp(String.raw`(?:^|[^<])>>?\s*${TEMP_PATH}(?=$|[\s;&|])`, "i"),
  new RegExp(
    String.raw`\btee\b(?:\s+-[^\s]+)*\s+${TEMP_PATH}(?=$|[\s;&|])`,
    "i",
  ),
  new RegExp(
    String.raw`\b(?:cp|mv|install)\b[^\n;&|]*\s${TEMP_PATH}\s*(?=$|[;&|])`,
    "i",
  ),
  new RegExp(
    String.raw`\b(?:curl|wget)\b[^\n;&|]*(?:\s(?:-o|--output|--output-document)(?:=|\s+))${TEMP_PATH}(?=$|[\s;&|])`,
    "i",
  ),
  new RegExp(
    String.raw`(?:^|\s)(?:--outdir|--output-dir|--output-path|--outfile|--log-file|--target-dir)(?:=|\s+)${TEMP_PATH}(?=$|[\s;&|])`,
    "i",
  ),
  new RegExp(String.raw`\bdd\b[^\n;&|]*\bof=${TEMP_PATH}(?=$|[\s;&|])`, "i"),
  new RegExp(
    String.raw`\b(?:truncate|fallocate)\b[^\n;&|]*\s${TEMP_PATH}(?=$|[\s;&|])`,
    "i",
  ),
  new RegExp(
    String.raw`\b(?:unzip\b[^\n;&|]*\s-d|tar\b[^\n;&|]*\s-C)\s+${TEMP_PATH}(?=$|[\s;&|])`,
    "i",
  ),
  new RegExp(
    String.raw`\b(?:fs|Deno)\.(?:writeFile|writeFileSync|writeTextFile|writeTextFileSync)\s*\(\s*["']${TEMP_PATH}`,
    "i",
  ),
  new RegExp(
    String.raw`\b[A-Za-z_][A-Za-z0-9_]*=${TEMP_PATH}(?=$|[\s;&|])`,
    "i",
  ),
]

const RECURSIVE_DELETE = [
  /(?:^|[;&|()]|\b(?:then|do|sudo|command|exec|env)\s+)\s*(?:(?:sudo|command|exec|env)(?:\s+-[^\s]+)*\s+)*(?:\/[^\s;|&]+\/)?rm\s+(?=[^;|&\n]*(?:-[^\s]*[rR]|--recursive\b))[^;|&\n]*/i,
  /\bfind\b[^;|&\n]*(?:-delete\b|-exec(?:dir)?\s+(?:\/[^\s;|&]+\/)?rm\b)/i,
  /\b(?:xargs\s+(?:-[^\s]+\s+)*(?:\/[^\s;|&]+\/)?rm|shutil\.rmtree|(?:fs\.|require\s*\(\s*["']fs["']\s*\)\.)(?:rm|rmSync)\s*\(|Deno\.remove\s*\(|Remove-Item\b[^;|&\n]*-Recurse)/i,
  /\brsync\b[^;|&\n]*--delete(?:-before|-during|-delay|-after|-excluded)?\b/i,
]

const MOUNT_CLEANUP = /\b(?:mount\s+--bind|mount\s+-o\s+bind|unshare\b)/i
const SHELL_VARIABLE =
  /(^|[^\\])(?:\$(?:[A-Za-z_][A-Za-z0-9_]*|\{[^}]+\}|\()|`)/
const FAIL_CLOSED_VARIABLE = /\$\{[A-Za-z_][A-Za-z0-9_]*:\?[^}]*\}/g

function shellWords(fragment: string): string[] {
  return fragment.match(/(?:"(?:\\.|[^"])*"|'[^']*'|\\.|[^\s])+/g) ?? []
}

function unquote(word: string): string {
  if (
    (word.startsWith("'") && word.endsWith("'")) ||
    (word.startsWith('"') && word.endsWith('"'))
  ) {
    return word.slice(1, -1)
  }
  return word
}

function rmTargets(fragment: string): string[] {
  const rmIndex = fragment.search(/\brm\b/i)
  if (rmIndex < 0) return []
  const words = shellWords(fragment.slice(rmIndex)).slice(1)
  const targets: string[] = []
  let optionsEnded = false
  for (const raw of words) {
    const word = unquote(raw).replace(/[;&|]+$/, "")
    if (!word) continue
    if (!optionsEnded && word === "--") {
      optionsEnded = true
      continue
    }
    if (!optionsEnded && word.startsWith("-")) continue
    targets.push(word)
  }
  return targets
}

function isHomeSpelling(target: string): boolean {
  return /^(?:~|~\/|\$HOME\/?|\$\{HOME\}\/?|\$\{HOME:\?[^}]*\}\/?)$/.test(
    target,
  )
}

function isRootSpelling(target: string): boolean {
  const normalized = target.replace(/\/+$/, "") || "/"
  return normalized === "/" || normalized === "/*"
}

function hasUnprotectedVariable(value: string): boolean {
  return SHELL_VARIABLE.test(value.replace(FAIL_CLOSED_VARIABLE, ""))
}

async function canonicalizeExisting(path: string): Promise<string> {
  let candidate = path
  const suffix: string[] = []
  while (true) {
    try {
      const existing = await realpath(candidate)
      return resolve(existing, ...suffix.reverse())
    } catch {
      const parent = dirname(candidate)
      if (parent === candidate) return resolve(path)
      suffix.push(
        candidate.slice(parent.length + (parent.endsWith("/") ? 0 : 1)),
      )
      candidate = parent
    }
  }
}

function isSamePath(left: string, right: string): boolean {
  return resolve(left) === resolve(right)
}

export const TEMPORARY_WORKSPACE_POLICY =
  "Prefer stdout or pipes when no file is needed. Before creating any disposable file, directory, download, log, screenshot, test artifact, or build artifact, call temporary_workspace_create with no arguments, use its returned path and autogenerated ID, and move retained outputs elsewhere before temporary_workspace_delete. Do not create scratch files under /tmp, $TMPDIR, ./tmp, ./temp, or another ad hoc temporary path."

function temporaryWorkspaceRemediation() {
  return `${TEMPORARY_WORKSPACE_POLICY} If an external tool creates artifacts outside your control, report their paths.`
}

function isManagedTemporaryPath(path: string): boolean {
  if (!isAbsolute(path)) return false
  const canonical = resolve(path)
  const roots = [
    resolve(tmpdir(), "pi-managed-workspaces"),
    resolve("/tmp/pi-managed-workspaces"),
    resolve("/private/tmp/pi-managed-workspaces"),
  ]

  return roots.some((root) => {
    const relation = relative(root, canonical)
    if (
      !relation ||
      relation === ".." ||
      relation.startsWith(`..${sep}`) ||
      isAbsolute(relation)
    ) {
      return false
    }
    return /^workspace-[^/]+(?:\/|$)/.test(relation)
  })
}

export function detectTemporaryPathWrite(
  path: string,
): DestructiveShellRisk | undefined {
  if (isManagedTemporaryPath(path)) return undefined
  const match = path.match(TEMP_PATH_PATTERN)
  if (!match) return undefined

  return {
    category: "Unmanaged temporary file or directory creation",
    matched: match[0],
    subject: path,
    hardBlock: true,
    remediation: temporaryWorkspaceRemediation(),
  }
}

export function detectTemporaryShellWrite(
  command: string,
): DestructiveShellRisk | undefined {
  const normalizedCommand = command.replace(/\\\r?\n/g, "")
  const match = TEMP_CREATION_PATTERNS.map((pattern) =>
    normalizedCommand.match(pattern),
  ).find(Boolean)
  if (!match) return undefined

  const matched = match[0].trim()
  const pathMatch = matched.match(TEMP_PATH_PATTERN)?.[0]
  if (pathMatch && isManagedTemporaryPath(pathMatch)) return undefined
  return {
    category: "Unmanaged temporary file or directory creation",
    matched: pathMatch ?? matched,
    subject: command,
    hardBlock: true,
    remediation: temporaryWorkspaceRemediation(),
  }
}

export async function detectDestructiveShellRisk(
  command: string,
  cwd: string,
): Promise<DestructiveShellRisk | undefined> {
  // Bash removes escaped newlines before parsing. Do the same so a model cannot
  // split `rm` and `-rf` across lines to bypass preflight checks.
  const normalizedCommand = command.replace(/\\\r?\n/g, "")
  const recursiveMatch = RECURSIVE_DELETE.map((pattern) =>
    normalizedCommand.match(pattern),
  ).find(Boolean)
  if (!recursiveMatch) {
    if (
      MOUNT_CLEANUP.test(normalizedCommand) &&
      /\b(?:rm\s+|rmtree)/i.test(normalizedCommand)
    ) {
      return {
        category: "Mount or temporary-directory cleanup",
        matched:
          "mount/namespace setup combined with automatic or recursive cleanup",
        subject: command,
      }
    }
    return undefined
  }

  const fragment = recursiveMatch[0]
  if (hasUnprotectedVariable(fragment)) {
    return {
      category: "Unsafe variable-expanded recursive deletion",
      matched:
        "recursive deletion target contains a shell variable without ${VAR:?message} fail-closed expansion",
      subject: command,
      hardBlock: true,
    }
  }

  const targets = rmTargets(fragment)
  for (const target of targets) {
    if (isRootSpelling(target) || isHomeSpelling(target)) {
      return {
        category: "Catastrophic recursive deletion target",
        matched: `target resolves syntactically to root or the home directory: ${target}`,
        subject: command,
        hardBlock: true,
      }
    }

    if (!/[`$*?{}[\]]/.test(target)) {
      const expanded = target.startsWith("~/")
        ? resolve(homedir(), target.slice(2))
        : isAbsolute(target)
          ? target
          : resolve(cwd, target)
      const canonical = await canonicalizeExisting(expanded)
      const canonicalHome = await canonicalizeExisting(homedir())
      const canonicalCwd = await canonicalizeExisting(cwd)
      if (
        isSamePath(canonical, canonicalHome) ||
        isSamePath(canonical, canonicalCwd)
      ) {
        return {
          category: "Catastrophic recursive deletion target",
          matched: `target canonicalizes to ${isSamePath(canonical, canonicalHome) ? "the home directory" : "the active workspace"}: ${canonical}`,
          subject: command,
          hardBlock: true,
        }
      }
    }
  }

  return {
    category: "Recursive or bulk deletion",
    matched: recursiveMatch[0],
    subject: command,
  }
}
